name: FNAmplifications
version: '${project.version}'
main: ne.fnfal113.fnamplifications.FNAmplifications
api-version: 1.16
authors: [ FN_FAL113 ]
description: Explore plethora of in-game items from machines, tools, pvp and many more!
website: https://github.com/FN-FAL113
depend: [ Slimefun ]
softdepend:
  - SimpleMaterialGenerators
  - Vault
commands:
  fngear:
    description: command for checking player worn FN Gears progress
    default: true
    usage: /<command>
  fnshockwavetest:
    description: command for testing shockwave effect from shockwave gem
    default: op
    usage: /<command>
permissions:
  fngear.levelupgears:
    description: for levelling up player worn FN Gears
    default: op
  fnshockwave.test:
    description: for testing shockwave shockwave effect from shockwave gem
    default: op
